---
anchor00_tag:
  anchor: 0x6a46
anchor01_tag:
  anchor: 0x6a66
anchor02_tag:
  anchor: 0x6a0c
anchor03_tag:
  anchor: 0x6a57
anchor04_tag:
  anchor: 0x6744
anchor05_tag:
  anchor: 0x6a48
anchor06_tag:
  anchor: 0x6a41
# anchor07_tag:
#   anchor: 0x6a60

anchorballs: # target id, can also be robots
 anchor00: 0x6a46
 anchor01: 0x6a66
 anchor02: 0x6a0c
 anchor03: 0x6a57
 anchor04: 0x6744
 anchor05: 0x6a48
 anchor06: 0x6a41
#  anchor07: 0x6a60
#  anchor08: 0x6a4a
#  anchor09: 0x6a46
#  anchor10: 0x6a46

anchorballs_count:
  anchor00: 1
  anchor01: 2
  anchor02: 3
  anchor03: 4
  anchor04: 5
  anchor05: 6
  anchor06: 7
  # anchor07: 8
  # anchor08: 9
  # anchor09: 10
  # anchor10: 11
